<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H8C69V7" ignored="0" name="SupermanTest" tests="57" failures="57" timestamp="2019-12-29T16:56:49 BDT" time="39.451" errors="0">
  <testcase name="LoginTest_InvalidUser" time="1.68" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Partner.FunctionalTest2.setUp(FunctionalTest2.java:97)
at Partner.FunctionalTest2.LoginTest_InvalidUser(FunctionalTest2.java:368)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest_InvalidUser -->
  <testcase name="LoginTest_InvalidUser" time="1.68" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.LoginTest_InvalidUser(FunctionalTest5.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest_InvalidUser -->
  <testcase name="SignupTest" time="0.568" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.SignupTest(FunctionalTest5.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- SignupTest -->
  <testcase name="SignupTest_AsPartner" time="0.608" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Partner.FunctionalTest2.setUp(FunctionalTest2.java:97)
at Partner.FunctionalTest2.SignupTest_AsPartner(FunctionalTest2.java:105)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- SignupTest_AsPartner -->
  <testcase name="CreateTrip_ForApprovedUser" time="0.075" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.CreateTrip_ForApprovedUser(FunctionalTest5.java:298)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- CreateTrip_ForApprovedUser -->
  <testcase name="checkTruckinPendingTab" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.checkTruckinPendingTab(FunctionalTest2.java:544)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- checkTruckinPendingTab -->
  <testcase name="getTripID_AndAcceptTrip_ByAdmin" time="1.577" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Utils.GIMSignIn.getauthToken(GIMSignIn.java:61)
at Customer.FunctionalTest5.getTripID_AndAcceptTrip_ByAdmin(FunctionalTest5.java:570)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getTripID_AndAcceptTrip_ByAdmin -->
  <testcase name="ApproveTruck_AndAddTracker" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.ApproveTruck_AndAddTracker(FunctionalTest2.java:552)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ApproveTruck_AndAddTracker -->
  <testcase name="CheckTruckisDisplayed_inApprovedTab" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.CheckTruckisDisplayed_inApprovedTab(FunctionalTest2.java:634)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- CheckTruckisDisplayed_inApprovedTab -->
  <testcase name="SearchforNonregisteredDriver_Validation" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.SearchforNonregisteredDriver_Validation(FunctionalTest2.java:650)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- SearchforNonregisteredDriver_Validation -->
  <testcase name="Register_NonregisteredDriverToGIMPlatform_Validation" time="0.004" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.Register_NonregisteredDriverToGIMPlatform_Validation(FunctionalTest2.java:664)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Register_NonregisteredDriverToGIMPlatform_Validation -->
  <testcase name="NewlyAddedDriver_isin_PendingState_Validation" time="0.0" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.NewlyAddedDriver_isin_PendingState_Validation(FunctionalTest2.java:757)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- NewlyAddedDriver_isin_PendingState_Validation -->
  <testcase name="AddNewTruck_withMandtoryFields_ToActivePartner" time="6.169" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Partner.HomeScreen.clickLoginButton(HomeScreen.java:43)
at Partner.FunctionalTest2.AddNewTruck_withMandtoryFields_ToActivePartner(FunctionalTest2.java:411)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- AddNewTruck_withMandtoryFields_ToActivePartner -->
  <testcase name="ApproveDriverByAdmin_and_ValidateDriverstatusonApp" time="5.139" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.ApproveDriverByAdmin_and_ValidateDriverstatusonApp(FunctionalTest2.java:776)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ApproveDriverByAdmin_and_ValidateDriverstatusonApp -->
  <testcase name="AcceptDriverAssociationRequest" time="3.145" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.AcceptDriverAssociationRequest(FunctionalTest2.java:802)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- AcceptDriverAssociationRequest -->
  <testcase name="AcceptBid" time="0.001" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.AcceptBid(FunctionalTest5.java:586)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- AcceptBid -->
  <testcase name="StartTrip_ByCustomer" time="0.004" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.StartTrip_ByCustomer(FunctionalTest5.java:641)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- StartTrip_ByCustomer -->
  <testcase name="CompleteTrip_ByCustomer" time="0.001" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.CompleteTrip_ByCustomer(FunctionalTest5.java:653)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- CompleteTrip_ByCustomer -->
  <testcase name="SubmitMyRating_DefaultRatings" time="0.002" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.NIDScreen.scrollTo(NIDScreen.java:163)
at Customer.FunctionalTest5.SubmitMyRating_DefaultRatings(FunctionalTest5.java:663)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- SubmitMyRating_DefaultRatings -->
  <testcase name="LaunchDashboard_VerifyCompletedTrip_isDisplayed_WithoutAnyFilters" time="0.002" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.LaunchDashboard_VerifyCompletedTrip_isDisplayed_WithoutAnyFilters(FunctionalTest5.java:677)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- LaunchDashboard_VerifyCompletedTrip_isDisplayed_WithoutAnyFilters -->
  <testcase name="VerifyTappingOnTriponDashboard_LandsUser_Onto_TripDetailsScreen" time="0.0" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.VerifyTappingOnTriponDashboard_LandsUser_Onto_TripDetailsScreen(FunctionalTest5.java:688)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- VerifyTappingOnTriponDashboard_LandsUser_Onto_TripDetailsScreen -->
  <testcase name="CreateTrip_And_CancelTrip" time="1.297" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.CreateTrip_And_CancelTrip(FunctionalTest5.java:708)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- CreateTrip_And_CancelTrip -->
  <testcase name="CreateTrip_ForPartnerToBid_AndThen_WithdrawBid" time="0.015" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Customer.MyTripsScreen.clickCreateTripIcon(MyTripsScreen.java:130)
at Customer.FunctionalTest5.CreateTrip_ForPartnerToBid_AndThen_WithdrawBid(FunctionalTest5.java:869)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- CreateTrip_ForPartnerToBid_AndThen_WithdrawBid -->
  <testcase name="PlaceBid_thenWithdrawBid" time="0.004" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.PlaceBid_thenWithdrawBid(FunctionalTest2.java:879)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- PlaceBid_thenWithdrawBid -->
  <testcase name="PlaceBidonTrip" time="5.004" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.PlaceBidonTrip(FunctionalTest2.java:816)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- PlaceBidonTrip -->
  <testcase name="AcceptPlacedBid_ByPartner" time="0.002" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.AcceptBid(FunctionalTest5.java:586)
at Customer.FunctionalTest5.AcceptPlacedBid_ByPartner(FunctionalTest5.java:1032)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- AcceptPlacedBid_ByPartner -->
  <testcase name="CancelWonBid" time="0.005" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.CancelWonBid(FunctionalTest2.java:913)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- CancelWonBid -->
  <testcase name="NoBidsToDisplayValidation_ForOngoingWonLostBids" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.NoBidsToDisplayValidation_ForOngoingWonLostBids(FunctionalTest2.java:938)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- NoBidsToDisplayValidation_ForOngoingWonLostBids -->
  <testcase name="InvoicePayments_Validation" time="0.004" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.InvoicePayments_Validation(FunctionalTest2.java:965)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- InvoicePayments_Validation -->
  <testcase name="AddNewTruckAndDriver_ToUseFor_EditTruckDriver_And_PlaceBid" time="0.01" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.AddNewTruckAndDriver_ToUseFor_EditTruckDriver_And_PlaceBid(FunctionalTest2.java:997)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- AddNewTruckAndDriver_ToUseFor_EditTruckDriver_And_PlaceBid -->
  <testcase name="AcceptNewPlacedBid_ByPartner" time="0.409" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.AcceptNewPlacedBid_ByPartner(FunctionalTest5.java:1037)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- AcceptNewPlacedBid_ByPartner -->
  <testcase name="EditTruckAndDriver_For_BookedTrip" time="0.002" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.EditTruckAndDriver_For_BookedTrip(FunctionalTest2.java:1150)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- EditTruckAndDriver_For_BookedTrip -->
  <testcase name="ValidateAmendedDriverTruck_ForBookedTrip" time="0.374" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.ValidateAmendedDriverTruck_ForBookedTrip(FunctionalTest5.java:1058)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ValidateAmendedDriverTruck_ForBookedTrip -->
  <testcase name="PartnerStartTrip" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.NIDScreen.scrollTo(NIDScreen.java:177)
at Partner.FunctionalTest2.PartnerStartTrip(FunctionalTest2.java:1208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- PartnerStartTrip -->
  <testcase name="PartnerEndTrip" time="0.0" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.NIDScreen.scrollTo(NIDScreen.java:177)
at Partner.FunctionalTest2.PartnerEndTrip(FunctionalTest2.java:1221)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- PartnerEndTrip -->
  <testcase name="ValidateEnglishtoBangla" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Partner.TrucksScreen.clickBurgerMenu(TrucksScreen.java:55)
at Partner.FunctionalTest2.ValidateEnglishtoBangla(FunctionalTest2.java:1234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidateEnglishtoBangla -->
  <testcase name="ValidateBanglatoEnglish" time="0.002" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.ValidateBanglatoEnglish(FunctionalTest2.java:1255)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidateBanglatoEnglish -->
  <testcase name="ValidateCustomerlistedNotifications_AreDisplayed" time="0.0" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.ValidateCustomerlistedNotifications_AreDisplayed(FunctionalTest5.java:1077)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidateCustomerlistedNotifications_AreDisplayed -->
  <testcase name="ValidatePartnerListedNotifications_AreDisplayed" time="0.403" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Partner.FunctionalTest2.setUp(FunctionalTest2.java:97)
at Partner.FunctionalTest2.ValidatePartnerListedNotifications_AreDisplayed(FunctionalTest2.java:1268)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ValidatePartnerListedNotifications_AreDisplayed -->
  <testcase name="CreateNewTrip" time="0.002" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Customer.MyTripsScreen.clickCreateTripIcon(MyTripsScreen.java:130)
at Customer.FunctionalTest5.CreateNewTrip(FunctionalTest5.java:1103)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- CreateNewTrip -->
  <testcase name="ValidateNewTripNotification_WhenTapped_Landsuser_onto_PlaceBidScreen" time="0.4" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Partner.FunctionalTest2.setUp(FunctionalTest2.java:97)
at Partner.FunctionalTest2.ValidateNewTripNotification_WhenTapped_Landsuser_onto_PlaceBidScreen(FunctionalTest2.java:1286)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ValidateNewTripNotification_WhenTapped_Landsuser_onto_PlaceBidScreen -->
  <testcase name="ValidateBidReceivedNotification_whenTapped_LandsUser_onto_BidListScreen" time="0.0" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.ValidateBidReceivedNotification_whenTapped_LandsUser_onto_BidListScreen(FunctionalTest5.java:1164)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ValidateBidReceivedNotification_whenTapped_LandsUser_onto_BidListScreen -->
  <testcase name="ValidateBidAcceptedNotification_Landsuser_onto_StarttripScreen" time="0.0" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.ValidateBidAcceptedNotification_Landsuser_onto_StarttripScreen(FunctionalTest2.java:1345)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidateBidAcceptedNotification_Landsuser_onto_StarttripScreen -->
  <testcase name="ValidateTripStartedNotification_WhenTapped_LandsUser_Onto_BookingDetailsScreen_Foruser_havingOption_toCompleteTrip" time="0.383" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.ValidateTripStartedNotification_WhenTapped_LandsUser_Onto_BookingDetailsScreen_Foruser_havingOption_toCompleteTrip(FunctionalTest5.java:1190)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ValidateTripStartedNotification_WhenTapped_LandsUser_Onto_BookingDetailsScreen_Foruser_havingOption_toCompleteTrip -->
  <testcase name="ValidateCompleteTripNotificationWhenTapped_Landsuser_onto_TripDetailsScreen" time="0.371" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Partner.FunctionalTest2.setUp(FunctionalTest2.java:97)
at Partner.FunctionalTest2.ValidateCompleteTripNotificationWhenTapped_Landsuser_onto_TripDetailsScreen(FunctionalTest2.java:1362)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.103\:5555 forward tcp\:8201 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ValidateCompleteTripNotificationWhenTapped_Landsuser_onto_TripDetailsScreen -->
  <testcase name="Validation_InvitingAlreadyRegisteredPartner_Tobe_Partner" time="0.002" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Partner.TrucksScreen.clickBurgerMenu(TrucksScreen.java:55)
at Partner.FunctionalTest2.Validation_InvitingAlreadyRegisteredPartner_Tobe_Partner(FunctionalTest2.java:1380)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Validation_InvitingAlreadyRegisteredPartner_Tobe_Partner -->
  <testcase name="Validation_InvitingAlreadyRegisteredCustomer_Tobe_Customer" time="0.0" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.Validation_InvitingAlreadyRegisteredCustomer_Tobe_Customer(FunctionalTest5.java:1209)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Validation_InvitingAlreadyRegisteredCustomer_Tobe_Customer -->
  <testcase name="Inviteuser_ToJoinAs_Partner" time="0.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.Inviteuser_ToJoinAs_Partner(FunctionalTest2.java:1397)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Inviteuser_ToJoinAs_Partner -->
  <testcase name="InviteUser_ToJoinAs_Customer" time="0.001" classname="Customer.FunctionalTest5">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Customer.FunctionalTest5.InviteUser_ToJoinAs_Customer(FunctionalTest5.java:1226)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- InviteUser_ToJoinAs_Customer -->
  <testcase name="Validation_RegisterasNewPartner_ByEnteringReferralCode_ofExistingPartner_whileRegistering" time="0.002" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Partner.HomeScreen.clickSignUpButton(HomeScreen.java:38)
at Partner.FunctionalTest2.Validation_RegisterasNewPartner_ByEnteringReferralCode_ofExistingPartner_whileRegistering(FunctionalTest2.java:1433)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Validation_RegisterasNewPartner_ByEnteringReferralCode_ofExistingPartner_whileRegistering -->
  <testcase name="Validation_RegisterasNewCustomer_ByEnteringReferralCode_ofExistingCustomer_WhileRegistering" time="0.807" classname="Customer.FunctionalTest5">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at Customer.FunctionalTest5.setUp(FunctionalTest5.java:101)
at Customer.FunctionalTest5.Validation_RegisterasNewCustomer_ByEnteringReferralCode_ofExistingCustomer_WhileRegistering(FunctionalTest5.java:1258)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'E:\\Software\\Eclipse\\SDK\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 192.168.110.101\:5555 forward tcp\:8202 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
... 35 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Validation_RegisterasNewCustomer_ByEnteringReferralCode_ofExistingCustomer_WhileRegistering -->
  <testcase name="Createnewtrip_withreferredcustomer" time="0.0" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.Createnewtrip_withreferredcustomer(FunctionalTest5.java:1438)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Createnewtrip_withreferredcustomer -->
  <testcase name="placeBidonTrip_ForFutureCancellation_AfterWinningBid" time="5.001" classname="Partner.FunctionalTest2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Partner.FunctionalTest2.PlaceBidonTrip(FunctionalTest2.java:816)
at Partner.FunctionalTest2.placeBidonTrip_ForFutureCancellation_AfterWinningBid(FunctionalTest2.java:904)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- placeBidonTrip_ForFutureCancellation_AfterWinningBid -->
  <testcase name="ReferredCustomer_completetrip_ByAcceptingBid_And_ValidateEarningsforFirstSuccessfulTripCompletion" time="0.002" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.ReferredCustomer_completetrip_ByAcceptingBid_And_ValidateEarningsforFirstSuccessfulTripCompletion(FunctionalTest5.java:1706)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ReferredCustomer_completetrip_ByAcceptingBid_And_ValidateEarningsforFirstSuccessfulTripCompletion -->
  <testcase name="validateearnings_for_firstcompletedtrip_referre" time="0.001" classname="Customer.FunctionalTest5">
    <failure type="java.lang.IllegalArgumentException" message="Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4">
      <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.android.AndroidElement field Customer.HomeScreen.LoginButton to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at Customer.HomeScreen.<init>(HomeScreen.java:24)
at Customer.FunctionalTest5.validateearnings_for_firstcompletedtrip_referre(FunctionalTest5.java:1785)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- validateearnings_for_firstcompletedtrip_referre -->
  <testcase name="ValidateEarnings_forreferre" time="0.004" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Partner.HomeScreen.clickLoginButton(HomeScreen.java:43)
at Partner.FunctionalTest2.ValidateEarnings_forreferre(FunctionalTest2.java:1892)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidateEarnings_forreferre -->
  <testcase name="placebidontrip_createdbyreferredcustomer_and_ValidateEarningsforreferredcustomer" time="2.031" classname="Partner.FunctionalTest2">
    <failure type="org.openqa.selenium.WebDriverException" message="java.lang.NullPointerException
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-H8C69V7&amp;apos;, ip: &amp;apos;192.168.110.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_121&amp;apos;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.WebDriverException: java.lang.NullPointerException
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-H8C69V7', ip: '192.168.110.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:192)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:1)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:99)
at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:119)
at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:59)
at org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4.click(<generated>)
at Partner.HomeScreen.clickLoginButton(HomeScreen.java:43)
at Partner.FunctionalTest2.placebidontrip_createdbyreferredcustomer_and_ValidateEarningsforreferredcustomer(FunctionalTest2.java:1594)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at io.appium.java_client.pagefactory.AppiumElementLocator.lambda$0(AppiumElementLocator.java:120)
at io.appium.java_client.pagefactory.AppiumElementLocator$WaitingFunction.apply(AppiumElementLocator.java:172)
... 23 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- placebidontrip_createdbyreferredcustomer_and_ValidateEarningsforreferredcustomer -->
</testsuite> <!-- SupermanTest -->
